### ISSUE TITLE
TypeError: full_lds_reset() got an unexpected keyword argument 'silent'

### ISSUE THREAD

**Issue by JS-Choi513** [tenstorrent/tt-burnin#1]
Run  `tt-burnin` after `pip3 install .` I got an error below:

```
Traceback (most recent call last):
  File "/home/deepgadget/.local/bin/tt-burnin", line 8, in <module>
    sys.exit(main())
  File "/home/deepgadget/.local/lib/python3.8/site-packages/tt_burnin/main.py", line 202, in main
    reset_all_devices(devices, reset_filename=args.reset)
  File "/home/deepgadget/.local/lib/python3.8/site-packages/tt_burnin/main.py", line 92, in reset_all_devices
    pci_board_reset(dev_ids, reinit=True)
  File "/home/deepgadget/.local/lib/python3.8/site-packages/tt_burnin/utils.py", line 52, in pci_board_reset
    WHChipReset().full_lds_reset(pci_interfaces=reset_wh_pci_idx, silent=True)
TypeError: full_lds_reset() got an unexpected keyword argument 'silent'
deepgadget@deepgadget:~/tt-burnin$ tt-burnin -h
usage: tt-burnin [-h] [-v] [--reset_file reset_config.json]
```
Then i comment out the `silent=True` in `.local/lib/python3.8/site-packages/tt_burnin/utils.py` tt-bunin is run without error. 
I don't know if this is working correctly

![image](https://github.com/tenstorrent/tt-burnin/assets/32115744/43682d8c-4e78-4122-a2ad-83f399b39240)

We have 2 Wormhole board(Please see the tt-smi output)

![image](https://github.com/tenstorrent/tt-burnin/assets/32115744/f1242193-181b-4b38-b27d-e3c4c3858f73)

**Comment by TTDRosen** [comment]
There's a bug in pip in versions prior to 24.0 where it will fetch the wrong package version when fetching git dependencies. Please try to reinstall with the latest version of pip.

As for your second question it is indeed working. I know because I can see in the telemetry output that chip tdp is running at the product limits and AICLK is throttling in response.

**Comment by TTDRosen** [comment]
And thanks for the comment! We are discussing how better to communicate that the program is working as intended.

**Comment by milank94** [comment]
@JS-Choi513 following up to see if this is still an issue you are experiencing. Has the above guidance been helpful?
